### ISSUE TITLE
it does not work with iOS 12

### ISSUE THREAD

**Issue by discepolo** [sfcd/SFProgressCircle#3]
Build failed using xCode 10 (beta).
Build successed using xCode 9+ but it is not correctly displayed installed on devices with iOS 12.

**Comment by KatekovAnton** [comment]
@discepolo please check now!

**Comment by discepolo** [comment]
Building with xCode9+ and run in iOS12 device the graphic issue is now fixed. Thanks.
But integrated using pod in xcode10 build failed.

Below the error:
![screen shot 2018-08-01 at 12 41 47](https://user-images.githubusercontent.com/23501122/43517351-b318b954-9588-11e8-8b85-adc3bc691d7d.png)

**Comment by KatekovAnton** [comment]
Had the same issue publishing pod with xcode10 and was not able to solve it.. seems like xcode beta problem...

**Comment by discepolo** [comment]
The issue with xCode 10 is still present on the GM version (not Beta).
Are there any news about it?

**Comment by siggb** [comment]
@discepolo Thanks for pointing on the mistake. Check out the new version `1.0.5`.
