### ISSUE TITLE
Example of SFCircleGradientLayer usage. Backdrop color?

### ISSUE THREAD

**Issue by tomisykora** [sfcd/SFProgressCircle#9]
Hello, 

Thanks for this plugin, i really dig the gradient, thats pretty cool! Anyway could you please provide an example of using this as a layer? I'm having trouble to get it working. I need to add some sort of icons to the start of the line and at the end as well so thats why i need to use it as a layer.

Also, nice feature would be to able toset a color of the backdrop.

Thanks in advance for any advice!

**Comment by KatekovAnton** [comment]
Hi. Do you want to add icon and make it moves animatedly together with the line? Do you need to rotate it to align with the current angle?

**Comment by tomisykora** [comment]
Hi @KatekovAnton, yes, the icons should move with the line and no, they don't need to be rotating.

I basically need something like bedtime control with fixed start point and without the time values. I created a custom control for that but i had trouble with circular gradient so i decided to go with this plugin.

**Comment by KatekovAnton** [comment]
you should add images to layer class, then override method
`- (void)drawInContext:(CGContextRef)ctx`
and call this  https://developer.apple.com/documentation/coregraphics/1454845-cgcontextdrawimage 


Something like this:
```
- (void)drawInContext:(CGContextRef)ctx
{
    [super drawInContext:ctx];
    [self drawWithSegmentNumber:_numSegments - 1 context:ctx];
    [self drawWithSegmentNumber:_numSegments context:ctx];
    
    if (self.image != nil) {
        CGPoint centerPoint = CGPointMake(CGRectGetMidX(self.bounds), CGRectGetMidY(self.bounds));
        float angle = self.startAngle + self.progress * (self.endAngle - self.startAngle);
        CGPoint p = CGPointMake(centerPoint.x-sinf(angle-M_PI_2)*_circleRadius, centerPoint.y+cosf(angle-M_PI_2)*_circleRadius);
        CGContextDrawImage(ctx, CGRectMake(p.x - 20, p.y - 20, 40, 40), self.image.CGImage);
    }
}
```

But you need to extend layer's borders to avoid clipping...
![c3f76093c66cdc55bcd58bcd99107615](https://user-images.githubusercontent.com/992894/62863867-0a9d8800-bd45-11e9-9a91-5a24a6df4f69.gif)

Hope it will help.

**Comment by tomisykora** [comment]
Cool, thanks for the effort, will try! :)
